config/routes.rb
Rails.application.routes.draw do
  resources :applications

  devise_for :users

  get 'welcome/index'

  root 'welcome#index'

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :user
  has_many :events, dependent: :destroy

  validates :url, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :application
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :applications, dependent: :destroy
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!, only: [:create]
  before_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def create
    app = Application.find_by(url: request.env['HTTP_ORIGIN'])

    if app
      @event = app.events.create(event_params)

      if @event.save
        render json: @event, status: :created
      else
        render json: {errors: @event.errors}, status: :unprocessable_entity
      end
    else
      render json: "Unregistered application", status: :unprocessable_entity
    end
  end

  def preflight
    head 200
  end

   private
   def event_params
     params.require(:event).permit(:name)
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  def index
    @app = Application.all
  end

  def show
    @app = Application.find(params[:id])
    @events = @app.events.group_by(&:name)
  end

  def new
    @app = Application.new
  end

  def create
    @app = Application.new
    @app.name = params[:application][:name]
    @app.url = params[:application][:url]

    if @app.save
      flash[:notice] = "Application was saved successfully."
      redirect_to @app
    else
      flash.now[:alert] = "There was an error saving the application. Please try again."
      render :new
    end
  end

  def edit
    @app = Application.find(params[:id])
  end

  def update
    @app = Application.find(params[:id])
    @app.name = params[:application][:name]
    @app.url = params[:application][:url]

    if @app.save
      flash[:notice] = "Application was updated successfully."
      redirect_to @app
    else
      flash.now[:alert] = "There was an error saving the Application. Please try again."
      render :edit
    end
  end

  def destroy
    @app = Application.find(params[:id])
    if @app.destroy
      flash[:notice] = "\"#{@app.name}\" was successfully unregistered."
      redirect_to applications_path
    else
      flash.now[:alert] = "There was an error unregistering the application."
      render :show
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @app = Application.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/applications/edit.html.erb
<div class = 'container'>
  <h3>Edit Application</h3>

  <%= form_for @app do |f| %>
    <div class = 'form-group'>
      <%= f.text_field :name, class: 'form-control', placeholder: "App Name" %>
      <br />
      <%= f.text_field :url, class: 'form-control', placeholder: "URL" %>
      <br />
      <%= f.submit "Save", class: 'btn btn-primary' %>&nbsp;&nbsp;<%= link_to "Cancel", :back %>
    </div>
  <% end %>
</div>

app/views/applications/index.html.erb
<div class = 'container'>
  <h1>All Applications</h1>

  <% @app.each do |application| %>
    <p><%= link_to application.name, application %></p>
  <% end %>
</div>

app/views/applications/new.html.erb
<div class = 'container'>
  <h3>New Application</h3>
  <%= form_for @app do |f| %>
    <div class = 'form-group'>
      <%= f.text_field :name, class: 'form-control', placeholder: 'App Name' %>
      <br />
      <%= f.text_field :url, class: 'form-control', placeholder: 'App URL' %>
      <br />
      <%= f.submit 'Save', class: 'btn btn-default' %>&nbsp;&nbsp;<%= link_to 'Cancel', :back %>
    </div>
  <% end %>
</div>

app/views/applications/show.html.erb
<div class = 'container'>
  <span style = 'font-size: 200%'><strong><%= @app.name %></strong></span>&nbsp;&nbsp;

  <%= link_to edit_application_path(@app) do %>
    <span style = 'font-size:11pt'>
      <span class='has-tooltip' data-toggle='tooltip' title='Edit App'>
        <span class = 'glyphicon glyphicon-pencil'></span>
      </span>
    </span>
  <% end %>
  &nbsp;&nbsp;
  <%= link_to @app, method: :delete, data: {confirm: 'Are you sure you want to unregister this application?'} do %>
    <span style = 'font-size:11pt'>
      <span class = 'has-tooltip' data-toggle='tooltip' title='Unregister App'>
        <span style = 'color:red' class = 'glyphicon glyphicon-trash'></span>
      </span>
    </span>
  <% end %>

  <br />
  <p><%= @app.url %></p>

  <h3>events</h3>
  <%= pie_chart @app.events.group(:name).count %><br /><br />
  <% @events.each do |event, count| %>
    <strong><%= "#{event}" %></strong>: <%= "#{count.length}" %><br />
    <%= line_chart @app.events.group_by_day(:created_at).count %><br />
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RocMetrics</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class = 'container'>
    <br />
    <% if user_signed_in? %>

        <%= link_to 'RocMetrics', root_url, style: "font-size: 250%; color:black; text-decoration: none;" %>
        <div class = 'pull-right', style = 'text-align: top'>
          Signed in as: <strong><%= current_user.email %></strong><br />
          <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %>
          | <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
        </div>

    <% end %>
    <br />
    <hr />
    <div class = 'flash'>
      <% if flash[:notice] %>
        <div class = 'alert alert-success'>
          <button type = 'button' class = 'close' data-dismiss = 'alert'>&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class = 'alert alert-warning'>
          <button type = 'button' class = 'close' data-dismiss = 'alert'>&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>
  </div>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class = 'container'>
  <span style = 'font-size:200%'><strong>All Applications</strong></span>
  &nbsp;&nbsp;
  <%= link_to "+ Register App", new_application_path, style: 'color:blue'%>
  <br /><br />
  <% @app.each do |application| %>
    <p><%= link_to application.name, application %></p>
  <% end %>

</div>